AllCops:
  TargetRubyVersion: 2.4

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/knife/director.rb'

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - let
    - let!
    - expect
    - git_source
